export enum PeriodEnum {
  PRESOCRATIC = "presocratic",
  SOCRATIC = "socratic",
  HELLENISTIC = "hellenistic",
  ROMAN = "roman",
  MEDIEVAL = "medieval",
  RENAISANCE = "renaissance",
  REASON = "reason",
  ENLIGHTENMENT = "enlightenment",
  MODERN = "modern",
}

export interface PhilType {
  lname: string;
  fname: string | "null";
  topname: string | "null";
  dates: string;
  period_id: number;
  nation: string;
  image: {
    url: string;
    desc: string;
  };
  text: {
    intro: string;
    life: string;
    work: string;
    books: string[];
  };
}

export const philosophers: PhilType[] = [
  {
    lname: "Abelard",
    fname: "Peter",
    topname: "",

    dates: "1079 - 1142",
    period_id: 5,
    nation: "French",
    image: {
      url: "https://www.philosophybasics.com/photos/abelard.jpg",
      desc: "Peter Abelard (and Héloïse) (From a 14th Century manuscript)",
    },
    text: {
      intro:
        "Peter Abelard (AKA Petrus Abaelardus or Pierre Abélard) (1079 - 1142) was a 12th Century French philosopher, theologian and logician of the Medieval period. He is mainly associated with the dominant Medieval movement of Scholasticism. He is probably most famous, however, for the story of his love affair with his student Héloïse which has become legendary as a romantic tale.",
      life:
        "Abelard was born in 1079 in the small village of Le Pallet (about 16km east of Nantes, in Brittany, France), the eldest son of a minor noble Breton family. He was a quick learner and his father encouraged him to study the liberal arts (dialectic, rhetoric and grammar). He particularly excelled in dialectic (or logic, which at that time consisted chiefly of the logic of Aristotle), and soon becoming a wandering Peripatetic academic rather than pursuing a military career like his father. <br> His early teacher was Roscellinus of Compiegne (c. 1050 - 1125), who is often regarded as the founder of Nominalism (the doctrine that abstract concepts, general terms or universals have no independent existence but exist only as names). In Paris, he was taught for a while by William of Champeaux (c. 1070 - 1122), a prominent Realist, and Abelard's arguments against Realism (and in favor of Nominalism and his own Conceptualism), were instrumental in the decline of Realism in the Middle Ages. <br> While still a young man, Abelard set up his own school at Melun and then at Paris, which proved very successful and, in 1115, at the age of 36, he was nominated canon of Notre-Dame Cathedral in Paris. At the peak of his fame, he attracted thousands of students from many countries of Europe. One of those students was Héloïse (d. 1164), and Abelard fell madly in love with her and caused a great scandal when she became pregnant. Héloïse has a son in secret and reluctantly agreed to Abelard's suggestion of a secret marriage. Her guardian, the canon Fulbert, found out about the marriage, broke into Abelard's chamber by night and castrated him. Héloïse, still only in her twenties, then became a nun for many years. Abelard returned to his teaching work, but was charged with heresy in 1121 over his rationalistic interpretation of the Trinitarian dogma (God in three persons), and he was confined to the convent of St. Medard at Soissons. Later he became a hermit, living in a cabin of reeds in a deserted part of the country, although students followed him even there. Gradually he recovered his respectability, and managed to establish Héloïse at Paraclete, and they continued a passionate but Platonic relationship, recorded in Abelard's autobiographical 'Historia Calamitatum'. In 1141, Abelard was again accused of heresy by St. Bernard of Clairvaux (1090 - 1153) in an attempt to crush Abelard's rationalistic inquiries, and he collapsed and died before being able to fully clear himself of the accusations.",
      work:
        "Much of Abelard's legacy lies in the quality of his Scholastic philosophizing and his attempt to give a formally rational expression to the received ecclesiastical doctrine. Although much of his work was condemned at the time, he paved the way for the ascendancy of the philosophical authority of Aristotle (rather than the Realism of Plato), which became firmly established in the half-century after his death. Abelard's attempt to bridge the gap between Realism and Nominalism became known as Conceptualism, the doctrine that universals (qualities or properties of an object which can exist in more than one place at the same time e.g. the quality of 'redness') exist only within the mind and have no external or substantial reality. Immanuel Kant later developed a modern Conceptualism, holding that universals have no connection with external things because they are exclusively produced by our a priori mental structures and functions. In theology, Pope Innocent III (1161 - 1216) accepted Abelard's Doctrine of Limbo, which amended St. Augustine's Doctrine of Original Sin, and which held that unbaptized babies did not, as at first believed, go straight to Hell, but to a special area of limbo, where they would feel no pain but no supernatural happiness either (because they would not yet be able to behold God). Perhaps Abelard's best known work is 'Sic et Non' ('Yes and No'), dating from between about 1121 and 1132, in which he pointed out apparently contradictory quotations from the Church Fathers on many of the traditional topics of Christian theology (such as multiple significations of a single word), and outlined rules for reconciling these contradictions. This work rekindled interest in the dialectic as a philosophical tool, and Abelard argued that dialectic (in addition to the Scriptures) was the road to the truth, as well as being good mental exercise. He made contributions to the field of Ethics, an area rarely touched on in Scholastic teaching, anticipating something of modern speculation with his idea that the moral character or value of human action is, at least to some extent, determined by subjective intention. Abelard was also long known as an important poet and composer, although very little remains of his work in this field.",
      books: [
        "Five Texts on the Mediaeval Problem of Universals: Porphyry, Boethius, Abelard, Duns Scotus, Ockham by Paul V. Spade (Translator)",
        "The Philosophy of Peter Abelard by John Marenbon (1999-09-28)",
        "The Letters of Abelard and Heloise (Penguin Classics) by Peter Abelard (Author), Heloise (Author), Michael Clanchy (Editor, Introduction), Betty Radice",
      ],
    },
  },
  {
    lname: "Albertus",
    fname: "Magnus",
    topname: "",
    dates: "c. 1206 - 1280",
    period_id: 5,
    nation: "German",
    image: {
      url: "https://www.philosophybasics.com/photos/albertus.jpg",
      desc: "Albertus Magnus (From a fresco in Treviso, Italy, 1352)",
    },
    text: {
      intro:
        "Albertus Magnus (AKA St. Albert the Great or Albert of Cologne) (c. 1200 - 1280) was a 13th Century German philosopher, theologian and scientist of the Medieval period. He is mainly associated with the dominant Medieval movement of Scholasticism, and his influence on the development of Scholastic philosophy in the 13th Century was enormous, especially his incorporation of Aristotelianism into the Christian west. He is also known as an early advocate for the peaceful coexistence of science and religion.",
      life:
        "Albertus was born, sometime between 1193 and 1206, to the knightly family of the Count of Bollstädt in Lauingen in Bavaria, Germany. He was educated principally at Padua in Italy, where he received instruction in Aristotle's writings. In 1223 he became a member of the Dominican Order, against the wishes of his family, and studied theology at Bologna in Italy and elsewhere. Later, he returned to Germany to teach at Cologne, Regensburg, Freiburg, Strasbourg and Hildesheim. In 1245 Albertus went to Paris to receive his doctorate and to become provincial of the Dominican Order. He taught for some time as a master of theology in Paris with great success, and it was during this period that his most famous student St. Thomas Aquinas began to study under him. He fulfilled duties as Bishop of Regensburg from 1260 to 1263, walking rather than riding across his huge diocese, and then spent the remainder of his life in semi-retirement, studying and preaching throughout southern Germany. He died in 1280 in Cologne, Germany, after two years of ill health. Contemporaries such as Roger Bacon and Dante Alighieri (1265 - 1321) applied the term 'Magnus' ('the Great') to Albertus during his own lifetime, referring to his immense reputation as a scholar and philosopher, and he remained steadfast in his defense of the orthodoxy of his former pupil, St. Thomas Aquinas, whose death in 1274 greatly grieved Albertus. He was beatified in 1622, and honored by the Catholic Church as a Doctor of the Church in 1931.",
      work:
        "Albertus wrote prolifically (his collected writings were collected into 38 volumes in 1899), and was perhaps the most widely read author of his time. He was famed for his literally encyclopedic knowledge of topics as diverse as logic, theology, psychology, botany, geography, astronomy, astrology, mineralogy, chemistry, zoology, physiology, phrenology and others. Most modern western knowledge of the works of Aristotle was preserved and presented by Albertus, and he digested, interpreted and systematized the whole of Aristotle's works (from the Latin translations and notes of Arabian commentators such as Averroës and Avicenna) in accordance with church doctrine, and with occasional divergences from the opinions of the master. His approach to this task, however, was clearly influenced by Neo-Platonism. His principal theological works are a commentary in three volumes on the 'Books of the Sentences' of Peter Lombard (c. 1100 - 1160), and his 'Summa Theologiae' in two volumes. Albertus's knowledge of physical science was considerable and (for the age) remarkably accurate, aided by his protracted study of Aristotle, which gave him great powers of systematic thought and exposition. He is credited with the discovery of the element arsenic, and there is much speculation on his work as an alchemist. He was certainly deeply interested in astrology, as were many scientists of the time, arguing that an understanding of the celestial influences affecting us could help us to live our lives more in accord with Christian precepts.Albertus is also known for his enlightening commentary on the musical practice of his times, and wrote extensively on proportions in music, on the ways in which music worked on the human soul, and on his categorical rejection of the popular notion of the 'music of the spheres'.",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Anaxagoras",
    topname: "",
    dates: "c. 500 - 428 B.C.",
    period_id: 1,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Anaximander",
    topname: "",
    dates: "c. 610 - 546 B.C.",
    period_id: 1,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Anaximenes",
    topname: "",
    dates: "c. 585 - 525 B.C.",
    period_id: 1,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "St. Anselm",
    topname: "",
    dates: "1033 - 1109",
    period_id: 5,
    nation: "Italian",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "St. Aquinas",
    fname: "Thomas",
    topname: "",
    dates: "1225 - 1274",
    period_id: 5,
    nation: "Italian",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Aristotle",
    topname: "",
    dates: "384 - 322 B.C.",
    period_id: 2,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "St. Augustine",
    topname: "of Hippo",
    dates: "A.D. 354 - 430",
    period_id: 4,
    nation: "Roman",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Averroës",
    topname: "",
    dates: "1126 - 1198",
    period_id: 5,
    nation: "Spanish-Arabic",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Avicenna",
    topname: "",
    dates: "980 - 1037",
    nation: "Persian",
    period_id: 5,
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Ayer",
    fname: "Alfred",
    topname: "",
    dates: "1910 - 1989",
    period_id: 9,
    nation: "English",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Bacon",
    fname: "Roger",
    topname: "",
    dates: "c. 1214 - 1294",
    period_id: 5,
    nation: "English",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Bacon",
    fname: "Sir Francis",
    topname: "",
    dates: "1561 - 1626",
    period_id: 6,
    nation: "English",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Bentham",
    fname: "Jeremy",
    topname: "",
    dates: "1749 - 1832",
    period_id: 9,
    nation: "English",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Berkeley",
    fname: "Bishop George",
    topname: "",
    dates: "1685 - 1753",
    period_id: 8,
    nation: "Irish",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Boethius",
    topname: "",
    dates: "c. A.D. 480 - 525",
    period_id: 4,
    nation: "Roman",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Burke",
    fname: "Edmund",
    topname: "",
    dates: "1729 - 1797",
    period_id: 8,
    nation: "Irish",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Cicero",
    fname: "Marcus Tullius",
    topname: "",
    dates: "106 - 43 B.C.",
    period_id: 4,
    nation: "Roman",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Comte",
    fname: "Auguste",
    topname: "",
    dates: "1798 - 1857",
    period_id: 9,
    nation: "French",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Democritus",
    topname: "",
    dates: "c. 460 - 370 B.C.",
    period_id: 1,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Derrida",
    fname: "Jacques",
    topname: "",
    dates: "1930 - 2004",
    period_id: 9,
    nation: "French",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Descartes",
    fname: "René",
    topname: "",
    dates: "1596 - 1650",
    period_id: 7,
    nation: "French",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Dewey",
    fname: "John",
    topname: "",
    dates: "1859 - 1952",
    period_id: 9,
    nation: "American",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Diogenes",
    topname: "of Sinope",
    dates: "c. 412 - 323 B.C.",
    period_id: 2,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Emerson",
    fname: "Ralph Waldo",
    topname: "",
    dates: "1803 - 1882",
    period_id: 9,
    nation: "American",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Empedocles",
    topname: "",
    dates: "c. 490 - 430 B.C.",
    period_id: 1,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Epictetus",
    topname: "",
    dates: "c. A.D. 55 - 135",
    period_id: 4,
    nation: "Greek-Roman",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Epicurus",
    topname: "",
    dates: "341 - 270 B.C.",
    period_id: 3,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Erasmus",
    fname: "Desiderius",
    topname: "",
    dates: "1466 - 1536",
    period_id: 6,
    nation: "Dutch",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Fichte",
    fname: "Johann Gottlieb",
    topname: "",
    dates: "1762 - 1814",
    period_id: 9,
    nation: "German",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Foucault",
    fname: "Michel",
    topname: "",
    dates: "1926 - 1984",
    period_id: 9,
    nation: "French",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Frege",
    fname: "Gottlob",
    topname: "",
    dates: "1848 - 1925",
    period_id: 9,
    nation: "German",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Gorgias",
    topname: "",
    dates: "c. 487 - 376 B.C.",
    period_id: 1,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Hegel",
    fname: "G.W.F.",
    topname: "",
    dates: "1770 - 1831",
    period_id: 9,
    nation: "German",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Heidegger",
    fname: "Martin",
    topname: "",
    dates: "1889 - 1976",
    period_id: 9,
    nation: "German",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Heraclitus",
    topname: "",
    dates: "c. 535 - 475 B.C.",
    period_id: 1,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Hobbes",
    fname: "Thomas",
    topname: "",
    dates: "1588 - 1679",
    period_id: 7,
    nation: "English",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Hume",
    fname: "David",
    topname: "",
    dates: "1711 - 1776",
    period_id: 8,
    nation: "Scottish",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Husserl",
    fname: "Edmund",
    topname: "",
    dates: "1859 - 1938",
    period_id: 9,
    nation: "German",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "James",
    fname: "William",
    topname: "",
    dates: "1842 - 1910",
    period_id: 9,
    nation: "American",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Kant",
    fname: "Immanuel",
    topname: "",
    dates: "1724 - 1804",
    period_id: 8,
    nation: "German",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Kierkegaard",
    fname: "Søren",
    topname: "",
    dates: "1813 - 1855",
    period_id: 9,
    nation: "Danish",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Leibniz",
    fname: "Gottfried Wilhelm",
    topname: "",
    dates: "1646 - 1716",
    period_id: 7,
    nation: "German",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Locke",
    fname: "John",
    topname: "",
    dates: "1632 - 1704",
    period_id: 7,
    nation: "English",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Machiavelli",
    fname: "Niccolò",
    topname: "",
    dates: "1469 - 1527",
    period_id: 6,
    nation: "Italian",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Maimonides",
    topname: "",
    dates: "1135 - 1204",
    period_id: 5,
    nation: "Spanish-Jewish",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Malebranche",
    fname: "Nicolas",
    topname: "",
    dates: "1638 - 1715",
    period_id: 7,
    nation: "French",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Marcus",
    fname: "Aurelius",
    topname: "",
    dates: "A.D. 121 -180",
    period_id: 4,
    nation: "Roman",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Marx",
    fname: "Karl",
    topname: "",
    dates: "1818 - 1883",
    period_id: 9,
    nation: "German",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Mill",
    fname: "John Stuart",
    topname: "",
    dates: "1806 - 1873",
    period_id: 9,
    nation: "English",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Moore",
    fname: "George Edward",
    topname: "",
    dates: "1873 - 1958",
    period_id: 9,
    nation: "English",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "More",
    fname: "Sir Thomas",
    topname: "",
    dates: "1478 - 1535",
    period_id: 6,
    nation: "English",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Nietzsche",
    fname: "Friedrich",
    topname: "",
    dates: "1844 - 1900",
    period_id: 9,
    nation: "German",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Ockham",
    fname: "William of",
    topname: "",
    dates: "c. 1285 - 1348",
    period_id: 5,
    nation: "English",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },

  {
    lname: "",
    fname: "Parmenides",
    topname: "of Elea",
    dates: "c. 515 - 450 B.C.",
    period_id: 1,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },

  {
    lname: "Pascal",
    fname: "Blaise",
    topname: "",
    dates: "1623 - 1662",
    period_id: 7,
    nation: "French",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Peirce",
    fname: "Charles Sanders",
    topname: "",
    dates: "1839 - 1914",
    period_id: 9,
    nation: "American",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Philo",
    topname: "of Alexandria",
    dates: "20 B.C. - A.D. 50",
    period_id: 3,
    nation: "Egyptian-Jewish",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Plato",
    topname: "",
    dates: "c. 428 - 348 B.C.",
    period_id: 2,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Plotinus",
    topname: "",
    dates: "A.D. 205 - 270",
    period_id: 3,
    nation: "Egyptian-Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Protagoras",
    topname: "",
    dates: "c. 490 - 420 B.C.",
    period_id: 1,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Pyrrho",
    topname: "",
    dates: "c. 360 - 270 B.C.",
    period_id: 3,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Pythagoras",
    topname: "",
    dates: "c. 570 - 490 B.C.",
    period_id: 1,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Quine",
    fname: "Willard Van Orman",
    topname: "",
    dates: "1908 - 2000",
    period_id: 9,
    nation: "American",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Rousseau",
    fname: "Jean-Jacques",
    topname: "",
    dates: "1712 - 1778",
    period_id: 8,
    nation: "Swiss-French",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Russell",
    fname: "Bertrand",
    topname: "",
    dates: "1872 - 1970",
    period_id: 9,
    nation: "English",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Ryle",
    fname: "Gilbert",
    topname: "",
    dates: "1900 - 1976",
    period_id: 9,
    nation: "English",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Sartre",
    fname: "Jean-Paul",
    topname: "",
    dates: "1905 - 1980",
    period_id: 9,
    nation: "French",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Schelling",
    fname: "Friedrich",
    topname: "",
    dates: "1775 - 1854",
    period_id: 9,
    nation: "German",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Schopenhauer",
    fname: "Arthur",
    topname: "",
    dates: "1788 - 1860",
    period_id: 9,
    nation: "German",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Scotus",
    fname: "John Duns",
    topname: "",
    dates: "c. 1266 - 1308",
    period_id: 5,
    nation: "Scottish",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Smith",
    fname: "Adam",
    topname: "",
    dates: "1723 - 1790",
    period_id: 8,
    nation: "Scottish",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Socrates",
    topname: "",
    dates: "464 - 399 B.C.",
    period_id: 2,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Spinoza",
    fname: "Baruch Benedict",
    topname: "",
    dates: "1623 - 1677",
    period_id: 7,
    nation: "Dutch-Jewish",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Thales",
    topname: "of Miletos",
    dates: "c. 624 - 546 B.C.",
    period_id: 1,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Thoreau",
    fname: "Henry David",
    topname: "",
    dates: "1817 - 1862",
    period_id: 9,
    nation: "American",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Voltaire",
    fname: "François Marie Arouet",
    topname: "",
    dates: "1694 - 1778",
    period_id: 8,
    nation: "French",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Whitehead",
    fname: "Alfred North",
    topname: "",
    dates: "1861 - 1947",
    period_id: 9,
    nation: "English",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "Wittgenstein",
    fname: "Ludwig",
    topname: "",
    dates: "1889 - 1951",
    period_id: 9,
    nation: "Austrian",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Zeno",
    topname: "of Citium",
    dates: "334 - 262 B.C.",
    period_id: 3,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
  {
    lname: "",
    fname: "Zeno",
    topname: "of Elea",
    dates: "c. 490 - 430 B.C.",
    period_id: 1,
    nation: "Greek",
    image: {
      url: "",
      desc: "",
    },
    text: {
      intro: "",
      life: "",
      work: "",
      books: [],
    },
  },
];
